"""
orchestrator/patch_transaction.py
===================================
Verify-Before-Commit transactional patch application (Gap A).

ARCHITECTURE
────────────
Every patch generated by FixerAgent must pass a compile/lint gate BEFORE it
touches the main working tree.  This module implements that gate using git
worktrees so the main checkout is never in a broken intermediate state.

Sequence
────────
1. Create a temporary git worktree at HEAD (same commit, new directory).
2. Apply the patch to the worktree copy of the file(s).
3. Run the language-appropriate compile/check gate on the patched file(s).
4. If PASS  → return PatchTransactionResult(ok=True). Caller can safely commit.
5. If FAIL  → log the failure, remove worktree, return ok=False.
   The main working tree is NEVER modified on failure.

Git stash fallback
──────────────────
When git worktrees are unavailable (shallow clone, detached HEAD without
a commit) the module falls back to git stash:

1. git stash push --include-untracked
2. Apply patch to working tree.
3. Run gate.
4. PASS  → git stash drop; return ok=True.
   FAIL  → git stash pop (restores original); return ok=False.

Public API
──────────
    from orchestrator.patch_transaction import PatchTransaction, PatchTransactionResult

    txn    = PatchTransaction(repo_root=Path("/my/repo"))
    result = await txn.apply_and_verify(
        fixed_files=fix.fixed_files,   # list[FixedFile]
        run_id=run_id,
    )
    if result.ok:
        # safe to commit to main working tree
        ...
    else:
        log.error("Patch failed gate: %s", result.failure_reason)

Integration with StabilizerController
──────────────────────────────────────
Call apply_and_verify() inside _phase_commit() BEFORE git add/commit.
If result.ok is False, mark the FixAttempt gate_passed=False and skip commit.
This prevents the main branch from ever receiving a syntactically or
semantically broken patch.
"""
from __future__ import annotations

import asyncio
import logging
import shutil
import subprocess
import tempfile
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)

# Default per-file gate timeout (seconds)
_GATE_TIMEOUT_S = 60


@dataclass
class PatchTransactionResult:
    """
    Result of a transactional patch verification attempt.

    Attributes
    ----------
    ok:
        True iff the patch applied cleanly AND passed all language gates.
    failure_reason:
        Human-readable description of the first failure encountered.
        Empty when ok=True.
    gate_output:
        Concatenated stdout+stderr from all gate commands run.
    worktree_path:
        Filesystem path of the temporary worktree used (may be empty when
        using the stash strategy or on total early failure).
    strategy:
        "worktree" or "stash" — which isolation strategy was used.
    """
    ok:             bool
    failure_reason: str  = ""
    gate_output:    str  = ""
    worktree_path:  str  = ""
    strategy:       str  = "worktree"


class PatchTransaction:
    """
    Transactional patch verification using git worktrees (primary) or
    git stash (fallback).

    Parameters
    ----------
    repo_root:
        Absolute path to the git repository root.
    gate_timeout_s:
        Maximum seconds for any single compile/lint gate subprocess.
    """

    def __init__(
        self,
        repo_root:      Path,
        gate_timeout_s: int = _GATE_TIMEOUT_S,
    ) -> None:
        self.repo_root      = Path(repo_root).resolve()
        self.gate_timeout_s = gate_timeout_s

    # ── Public entry point ────────────────────────────────────────────────────

    async def apply_and_verify(
        self,
        fixed_files: list[Any],   # list[brain.schemas.FixedFile]
        run_id:      str = "",
    ) -> PatchTransactionResult:
        """
        Apply *fixed_files* to an isolated worktree/stash and run the
        language-appropriate compile gate.

        Returns PatchTransactionResult.ok=True only when:
          • every patch/content write succeeds, AND
          • every file passes its language gate (ruff+mypy, clang-tidy, etc.)

        The main working tree is NEVER modified on failure.
        """
        if not fixed_files:
            return PatchTransactionResult(ok=True, failure_reason="no files to patch")

        # Prefer worktree isolation — fall back to stash if unavailable
        if await self._worktrees_available():
            return await self._apply_via_worktree(fixed_files, run_id)
        else:
            log.warning(
                "[PatchTransaction] git worktrees unavailable — "
                "falling back to stash strategy"
            )
            return await self._apply_via_stash(fixed_files, run_id)

    # ── Worktree strategy ─────────────────────────────────────────────────────

    async def _worktrees_available(self) -> bool:
        """Return True when the repo supports `git worktree add`."""
        ok, _ = await self._run_cmd(
            ["git", "-C", str(self.repo_root), "worktree", "list", "--porcelain"],
            timeout=10,
        )
        return ok

    async def _apply_via_worktree(
        self,
        fixed_files: list[Any],
        run_id:      str,
    ) -> PatchTransactionResult:
        wt_tag  = run_id[:8] if run_id else uuid.uuid4().hex[:8]
        wt_name = f"rhodawk-verify-{wt_tag}"
        wt_path = Path(tempfile.gettempdir()) / wt_name

        # Create an isolated worktree at HEAD
        ok, err = await self._run_cmd([
            "git", "-C", str(self.repo_root),
            "worktree", "add", "--detach", str(wt_path),
        ])
        if not ok:
            return PatchTransactionResult(
                ok=False,
                failure_reason=f"git worktree add failed: {err[:400]}",
                strategy="worktree",
            )

        result = PatchTransactionResult(ok=False, strategy="worktree")
        try:
            result = await self._apply_and_gate(wt_path, fixed_files, "worktree")
        finally:
            await self._remove_worktree(wt_path)
        return result

    async def _remove_worktree(self, wt_path: Path) -> None:
        """Unconditionally remove a worktree — called in finally blocks."""
        await self._run_cmd([
            "git", "-C", str(self.repo_root),
            "worktree", "remove", "--force", str(wt_path),
        ])
        # Belt-and-suspenders: rmtree if git didn't clean up
        if wt_path.exists():
            try:
                shutil.rmtree(wt_path, ignore_errors=True)
            except Exception:
                pass

    # ── Stash fallback strategy ───────────────────────────────────────────────

    async def _apply_via_stash(
        self,
        fixed_files: list[Any],
        run_id:      str,
    ) -> PatchTransactionResult:
        stash_msg = f"rhodawk-verify-{run_id[:8] or 'patch'}"

        # Stash working-tree changes so we start from a clean HEAD state
        stash_ok, stash_out = await self._run_cmd([
            "git", "-C", str(self.repo_root),
            "stash", "push", "--include-untracked", "-m", stash_msg,
        ])
        stash_created = stash_ok and "No local changes" not in stash_out

        result = PatchTransactionResult(ok=False, strategy="stash")
        try:
            result = await self._apply_and_gate(
                self.repo_root, fixed_files, "stash"
            )
        finally:
            if stash_created:
                if result.ok:
                    # Gate passed — clean up stash so it doesn't accumulate
                    await self._run_cmd([
                        "git", "-C", str(self.repo_root), "stash", "drop",
                    ])
                else:
                    # Gate failed — restore the original working tree
                    await self._run_cmd([
                        "git", "-C", str(self.repo_root), "stash", "pop",
                    ])
        return result

    # ── Core apply + gate logic ───────────────────────────────────────────────

    async def _apply_and_gate(
        self,
        root:        Path,
        fixed_files: list[Any],
        strategy:    str,
    ) -> PatchTransactionResult:
        """
        Write *fixed_files* into *root* and run the per-file compile gate.

        On the first gate failure the method returns immediately so that the
        expensive gate for later files is skipped and the failure is clear.
        """
        # Local import to avoid circular dependency at module level
        from brain.schemas import PatchMode  # type: ignore[import]

        gate_outputs: list[str] = []

        for ff in fixed_files:
            target = (root / ff.path).resolve()

            # Validate that the target is inside root (path-traversal guard)
            try:
                target.relative_to(root)
            except ValueError:
                return PatchTransactionResult(
                    ok=False,
                    failure_reason=(
                        f"Path traversal detected: {ff.path!r} resolves "
                        f"outside repo root {root}"
                    ),
                    strategy=strategy,
                )

            target.parent.mkdir(parents=True, exist_ok=True)

            # ── Apply patch or write full file ────────────────────────────────
            if getattr(ff, "patch_mode", None) == PatchMode.UNIFIED_DIFF and ff.patch:
                patch_ok, patch_out = await self._apply_patch(target, ff.patch)
                gate_outputs.append(f"[patch] {ff.path}: {'OK' if patch_ok else 'FAIL'}")
                if not patch_out.strip():
                    patch_out = "(no output)"
                gate_outputs.append(patch_out[:600])
                if not patch_ok:
                    return PatchTransactionResult(
                        ok=False,
                        failure_reason=(
                            f"patch(1) failed on {ff.path}:\n{patch_out[:500]}"
                        ),
                        gate_output="\n".join(gate_outputs),
                        strategy=strategy,
                    )
            elif getattr(ff, "content", ""):
                target.write_text(ff.content, encoding="utf-8")
                gate_outputs.append(f"[write] {ff.path}: OK")
            else:
                # No patch and no content — skip this file
                log.debug(
                    "[PatchTransaction] %s: no content or patch — skipping gate",
                    ff.path,
                )
                continue

            # ── Run language gate ─────────────────────────────────────────────
            gate_ok, gate_out = await self._run_gate(root, ff.path)
            gate_outputs.append(f"[gate] {ff.path}: {'PASS' if gate_ok else 'FAIL'}")
            gate_outputs.append(gate_out[:800])
            if not gate_ok:
                return PatchTransactionResult(
                    ok=False,
                    failure_reason=(
                        f"Compile/lint gate FAILED for {ff.path}:\n{gate_out[:600]}"
                    ),
                    gate_output="\n".join(gate_outputs),
                    worktree_path=str(root),
                    strategy=strategy,
                )

        return PatchTransactionResult(
            ok=True,
            gate_output="\n".join(gate_outputs),
            worktree_path=str(root),
            strategy=strategy,
        )

    # ── Patch application ─────────────────────────────────────────────────────

    async def _apply_patch(self, target: Path, patch: str) -> tuple[bool, str]:
        """Apply a unified diff to *target* using the patch(1) command."""
        try:
            proc = await asyncio.create_subprocess_exec(
                "patch", "--forward", "-p0", str(target),
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            stdout, stderr = await asyncio.wait_for(
                proc.communicate(patch.encode("utf-8", errors="replace")),
                timeout=30,
            )
            ok  = proc.returncode == 0
            out = (stdout + stderr).decode("utf-8", errors="replace")
            return ok, out
        except asyncio.TimeoutError:
            return False, "patch(1) timed out after 30 s"
        except FileNotFoundError:
            # patch(1) not available — accept the file write and skip the gate
            log.warning(
                "[PatchTransaction] patch(1) not found — "
                "accepting patch without apply verification"
            )
            return True, "patch(1) not installed — skipped"
        except Exception as exc:
            return False, f"patch command error: {exc}"

    # ── Language gates ────────────────────────────────────────────────────────

    async def _run_gate(self, root: Path, rel_path: str) -> tuple[bool, str]:
        """
        Run the language-appropriate static check on a single patched file.

        Gate map (by file extension):
          .py / .pyi   → ruff (E,F,W) + mypy --ignore-missing-imports
          .c/.cpp/.h   → clang-tidy, or gcc -fsyntax-only as fallback
          .js/.mjs     → node --check (syntax only)
          .ts          → tsc --noEmit
          .go          → go vet
          .java        → javac -proc:none
          .rs          → rustc --emit=metadata --crate-type=lib
          other        → no gate (pass-through)

        Tool-not-found is treated as a pass-through rather than a failure so
        that deployments without the full toolchain still function — the gate
        is best-effort, not a hard dependency.
        """
        ext      = Path(rel_path).suffix.lower()
        abs_path = str((root / rel_path).resolve())

        if ext in (".py", ".pyi"):
            return await self._gate_python(abs_path)
        if ext in (".c", ".cpp", ".cc", ".cxx", ".h", ".hpp", ".hxx"):
            return await self._gate_c(abs_path)
        if ext in (".js", ".mjs", ".cjs"):
            return await self._gate_js(abs_path)
        if ext == ".ts":
            return await self._gate_ts(root, abs_path)
        if ext == ".go":
            return await self._gate_go(root, abs_path)
        if ext == ".java":
            return await self._gate_java(abs_path)
        if ext == ".rs":
            return await self._gate_rust(root, abs_path)
        return True, f"no gate configured for {ext!r}"

    async def _gate_python(self, abs_path: str) -> tuple[bool, str]:
        ruff_ok, ruff_out = await self._run_cmd(
            ["ruff", "check", "--select=E,F,W", "--no-cache", abs_path]
        )
        if not ruff_ok:
            return False, f"ruff:\n{ruff_out}"
        mypy_ok, mypy_out = await self._run_cmd(
            ["mypy", "--ignore-missing-imports", "--no-error-summary", abs_path]
        )
        if not mypy_ok:
            return False, f"mypy:\n{mypy_out}"
        return True, f"ruff+mypy PASS: {abs_path}"

    async def _gate_c(self, abs_path: str) -> tuple[bool, str]:
        # Prefer clang-tidy for richer analysis
        ok, out = await self._run_cmd(
            ["clang-tidy", "--quiet", abs_path, "--", "-std=c11", "-Wall"]
        )
        if "not found" not in out and "No such" not in out:
            return ok, f"clang-tidy:\n{out}"
        # Fall back to compiler syntax check
        ok, out = await self._run_cmd(
            ["gcc", "-fsyntax-only", "-std=c11", "-Wall", "-Wextra", abs_path]
        )
        return ok, f"gcc -fsyntax-only:\n{out}"

    async def _gate_js(self, abs_path: str) -> tuple[bool, str]:
        return await self._run_cmd(["node", "--check", abs_path])

    async def _gate_ts(self, root: Path, abs_path: str) -> tuple[bool, str]:
        return await self._run_cmd(
            ["tsc", "--noEmit", "--allowJs", "--strict", abs_path],
            cwd=str(root),
        )

    async def _gate_go(self, root: Path, abs_path: str) -> tuple[bool, str]:
        return await self._run_cmd(["go", "vet", abs_path], cwd=str(root))

    async def _gate_java(self, abs_path: str) -> tuple[bool, str]:
        return await self._run_cmd(["javac", "-proc:none", abs_path])

    async def _gate_rust(self, root: Path, abs_path: str) -> tuple[bool, str]:
        return await self._run_cmd([
            "rustc", "--edition=2021", "--crate-type=lib",
            "--emit=metadata", "-o", "/dev/null", abs_path,
        ], cwd=str(root))

    # ── Subprocess helper ─────────────────────────────────────────────────────

    async def _run_cmd(
        self,
        cmd:     list[str],
        cwd:     str | None = None,
        timeout: int | None = None,
    ) -> tuple[bool, str]:
        """
        Run *cmd* as a subprocess and return (ok, combined_output).

        FileNotFoundError (tool not installed) is returned as ok=True with a
        "skipped" note so missing tools never block the pipeline.
        """
        t = timeout or self.gate_timeout_s
        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                cwd=cwd,
            )
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=t)
            ok  = proc.returncode == 0
            out = (stdout + stderr).decode("utf-8", errors="replace")
            return ok, out
        except asyncio.TimeoutError:
            log.warning("[PatchTransaction] gate command timed out: %s", cmd[0])
            return False, f"command timed out after {t} s"
        except FileNotFoundError:
            log.debug(
                "[PatchTransaction] gate tool not found: %s — skipping", cmd[0]
            )
            return True, f"{cmd[0]} not installed — gate skipped"
        except Exception as exc:
            return False, f"subprocess error: {exc}"
